apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: simple-topic-demo
  labels:
    strimzi.io/cluster: kafka-cluster-demo
spec:
  config:
    # 60m * 60s * 1000ms = 1h
    retention.ms: 3600000
    # 1gb
    segment.bytes: 1073741824
  partitions: 1
  replicas: 2